server:
  port: 13321

spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&AllowPublicKeyRetrieval=True
    username: root
    password: root
  cloud:
    alibaba:
      seata:
        tx-service-group: demo-group

dubbo:
  registry:
    address: zookeeper://localhost:2181

mybatis:
  mapper-locations: classpath:mapper/*.xml

seata:
  service:
    vgroup-mapping:
      demo-group: default
  registry:
    type: zk
    zk:
      server-addr: localhost:2181
